services:
  - type: web
    name: spainroom-cedula
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_verify_cedula:app -k gthread --threads 4 --timeout 120 --bind 0.0.0.0:$PORT
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
